import Head from "next/head";
import { Manrope } from 'next/font/google'
import Logo from "~/components/Logo";
import Hero from "~/components/Hero";
import Benefits from "~/components/Benefits";
import Plans from "~/components/Plans";
import Notifier from "~/components/Notifier";

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope'
})

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${manrope.variable}` + " font-manrope flex min-h-screen flex-col items-center gap-[144px] text-white bg-abyss"}>
        <Hero />
        <Benefits />
        <Plans />
        <Notifier />
      </main>
    </>
  );
}
